csi-addons/kubernetes-csi-addons

api/v1beta1/csiaddonsnode_types.go
docs/csiaddonsnode.md

This commit adds CSIAddonsNode API.
Currently the API is designed such that we will have
single CSIAddonsNode per side-car.
Alternatively, we can have single CSIAddonsNode per host.
Related: csi-addons/spec#28

api: adds CSIAddonsNode api

---

api/v1alpha1/reclaimspacejob_types.go
docs/reclaimspace.md

ReclaimSpaceJob is a namespaced custom resource designed to invoke reclaim space operation on target volume.
```yaml
apiVersion: csiaddons.openshift.io/v1beta1
kind: ReclaimSpaceJob
metadata:
name: sample-1
spec:
target:
pvc: pvc-1
backOffLimit: 10
activeDeadlineSeconds: 900
```
+ `target` represents the volume target on which the reclaim space operation will be performed.
+ `pvc` contains a string indicating the name of `PersistentVolumeClaim`.
+ `backOfflimit` specifies the number of retries before marking reclaim space operation as failed. If not specified, defaults to 6.
+ `activeDeadlineSeconds` specifies the duration in seconds relative to the startTime that the operation might be retried; value must be positive integer. If not specified, defaults to 600 seconds.
Signed-off-by: …

api: add ReclaimSpaceJob api

---

api/v1alpha1/reclaimspacejob_types.go

ReclaimSpaceJob CR creation will fail as the parameter `retryDeadlineSeconds` will mismatch the one in CRD  `json:"activeDeadlineSeconds"`.
Signed-off-by: Yug Gupta <yuggupta27@gmail.com>

bug: correct activedeadline to retrydeadline

---

.github/workflows/build-push.yaml
.github/workflows/test-build.yaml

Two CI jobs are added:
1. Test building container images, so that Mergify can require 
`build_controller` and `build_sidecar` as CI jobs.
2. The container images should get pushed to quay.io after a PR has been
merged. This currently builds the container images for all the
architectures that the golang base container and Docker Actions support.

ci: add GitHub Workflow for building and pushing container-images

---

.github/dependabot.yml
.github/mergify.yml

In addition to the requirement of passing test container builds, the `vendor` label is set for vendored dependencies.
By default Dependabot labels PRs it creates with `dependency`. As this
is a Golang project, we ideally use `vendor` instead. This needs adoption in the Dependabot config too.

ci: require passing test builds before merge

---

.github/workflows/build-push.yaml
.github/workflows/test-build.yaml

It seems that quay.io does not allow a dash `-` in the name of the
organization. Therefore images should get tagged and pushed to
quay.io/csiaddons.
Closes: #11

build: tag images under the quay.io/csiaddons org

---

.github/workflows/build-push.yaml
.github/workflows/test-build.yaml

To fasten the CI jobs for testing builds, build container images only on one arch and when pushing build on all arch.

ci: build container image on one arch

---

internal/connection/connection.go
internal/connection/connection_pool.go
internal/connection/connection_pool_test.go

Connection object will contain required details for controllers
to decide to which client to connect to.
connectionPool contains a map of connection object,
which required functions Put, Delete and Get.
---
A single ConnectionPool Object will be created in main.go and shared between all controllers.
CSIAddonsNode controller will take care of adding and deleting connections, while other controller can get the list and decide which connection to use.

controller: add connection package 

---

.github/mergify.yml

The jobs in the .github/workflows/test-golang.yaml workflow are stable
and pass on the current main branch. These jobs can now be required for
merging PRs.
**_Note:_** this requires manual merging as it updates the Mergify config.

Require passing of Golang CI jobs before merging

---

.github/workflows/test-golang.yaml

making job name same as job to make the mergify rules match the github status.

ci: make job name same as job

---

Makefile
README.md

Deploying with `make deploy` is the easiest while testing and
developing. This is the recommended method for now.
Updates: #14

doc: add a minimal description for `make deploy`

---

sidecar/internal/csiaddonsnode/csiaddonsnode.go
sidecar/internal/csiaddonsnode/csiaddonsnode_test.go
sidecar/internal/server/server.go
sidecar/internal/util/util.go
sidecar/internal/util/util_test.go
sidecar/main.go

Just using port to start controller server leads to
grpc server listening on all available ip addresses.
This causes plugin pod running on host network to listen
to requests pointed towards pod ips on that particular port
which is undesirable.
Using `<POD_IP>:<PORT>` makes sure grpc server is listening
on its intended endpoint.

sidecar: use <POD_IP>:<PORT> for controller endpoint

---

.github/mergify.yml

Mergifyio is deprecating `merge` action, which will
be replaced by `queue` action.
https://blog.mergify.com/strict-mode-deprecation/
This commit makes necessary changes for the same.
Refer: https://docs.mergify.com/actions/queue/

ci: update mergifyio config to use queue action

---

sidecar/internal/server/server.go

Earlier the logs contained an entry like the following when the sidecar
started to listen:
I0107 13:35:07.438390  329335 server.go:89] Listening for CSI-Addons requests on address: &net.TCPAddr{IP:net.IP{0xa, 0x0, 0x99, 0xe6}, Port:4080, Zone:""}
This is not particular readable. In the future, the log will contain:
I0107 13:46:25.058413  341537 server.go:89] Listening for CSI-Addons requests on address: 10.0.153.230:4080

logging: show the listening address in readable format

---

sidecar/internal/csiaddonsnode/csiaddonsnode.go

In case creating the CSIAddonsNode for a Pod fails, a retry is done.
There are several causes that can cause failures, these seem to be the
most common ones:
- User cannot create resource "csiaddonsnodes" in API group "csiaddons.openshift.io"
- no kind "CSIAddonsNode" is registered for the internal version of group "csiaddons.openshift.io"
In the above cases, either the RBAC is limiting access to the API, or
the CRD is not available in the Kubernetes cluster.
Updates: #48

sidecar: retry creating CSIAddonsNode on failure

---

sidecar/internal/csiaddonsnode/csiaddonsnode.go

When the sidecar starts, the following fatal error is logged:
failed to create csiaddonsnode object: no kind "CSIAddonsNode" is registered for the internal version of group "csiaddons.openshift.io" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:74"
After that, the sidecar restarts.
Even though the error is handled as fatal, the new CSIAddonsNode object
is created successfully. After the restart, the new CSIAddonsNode is
found, and the sidecar continues to startup successfully.
It seems that placing the result `Into(nil)` causes the failure, as
opposed to the documentation. Getting the error from the `Do()` response
is sufficient here, and prevents the failure of calling `Into()`.

sidecar: prevent failure and listen immediately

---

sidecar/internal/client/client.go
sidecar/internal/csiaddonsnode/csiaddonsnode.go
sidecar/internal/csiaddonsnode/csiaddonsnode_test.go
sidecar/main.go

Using environment variables makes it difficult to see what parameters
are used by the sidecar. Instead of reading some configuration options
from environment variables, use parameters for the executable for all
options.

sidecar: pass Pod details as parameters

---

internal/connection/connection_pool.go
internal/connection/connection_pool_test.go

This commit modifies ConnectionPool.Get() to take in
driverName and optional nodeID as parameters and now
returns a filtered copy of connections map.
This is done to avoid any deadlock issue that can occur
when unlock function may not be called in previous iteration
of the function.
Unit tests have been added and it now uses assert package.
- Further filtering using Capabilities seems a bit tricky, It can be done as a future enhancement.

controller: modify ConnectionPool.Get() to return a copy

---

.github/workflows/build-push.yaml

When the GitHub Worflow to push the bundle container-image runs, it uses
the standard version of Go that is installed on the Ubuntu worker. This
version does not work while building `kustomize`:
go build -o /home/runner/work/kubernetes-csi-addons/kubernetes-csi-addons/bin/kustomize ./vendor/sigs.k8s.io/kustomize/kustomize/v4
vendor/sigs.k8s.io/kustomize/kyaml/filesys/fsondisk.go:115:21: undefined: os.ReadDir
The project requires Go 1.17, so we should use that while building the
bundle container-image as well.
Fixes: https://github.com/csi-addons/kubernetes-csi-addons/runs/4798369471?check_suite_focus=true

build: use Golang 1.17 when building the bundle container-image

---

.github/workflows/tag-release.yaml

When a release is tagged, the GitHub workflow will build the container
images and push them to Quay.io with the `:<git-tag>` version.
A test-run (without publishing) is available in my [personal fork](https://github.com/nixpanic/kubernetes-csi-addons/runs/4801220182?check_suite_focus=true).

build: publish versioned container-images on pushing a git tag

---

.github/workflows/tag-release.yaml
Makefile

The bundle container-image always includes `:latest` as the tag for the
controller image. This is not really appropriate, as some bundles will
be generated for a tagged release. When a bundle is tagged with a
release, it should refer to the same version of the controller
container-image.

build: use the tagged version in the release bundle

---

Makefile
config/manifests/bases/csi-addons.clusterserviceversion.yaml

The controller image-name should use the `TAG` just as other images.
When this is not done, the bundle includes the following reference to
the image, and fails to deploy:
quay.io/csiaddons/k8s-controller:latest:latest`
By using `TAG` as the other container images do, the bundle will refer
to the image with `:latest`, or the `TAG` that was used for creating a
release.
The InstallMode `OwnNamespace` is required for deploying with
odf-operator. If this is not set, deploying fails with the following
error:
OwnNamespace InstallModeType not supported, cannot configure to watch own namespace
Tested-with: red-hat-storage/odf-operator#165

bundle: drop fixed `:latest` version from controller image-name

---

cmd/manager/main.go
controllers/networkfence_controller.go

The `NetworkFence` controller watches of Networkfence Custom Resources and sends:
- `FenceClusterNetwork` request on a NetworkFence CR creation.
- `UnfenceClusterNetwork` request on the NetworkFence CR deletion.

Add NetworkFence Controller

---

Makefile
config/crd/bases/csiaddons.openshift.io_csiaddonsnodes.yaml
config/crd/bases/csiaddons.openshift.io_networkfences.yaml
config/crd/bases/csiaddons.openshift.io_reclaimspacejobs.yaml
config/rbac/role.yaml

The `paths=` option to `controller-gen` is not correct, it does not
generate all the required files. By using the `paths={...}` syntax, it
seems to do what is intended.
Also, `./api` was missing, so new CRDs would not get created either.

build: fix manifest generation

---

api/v1alpha1/networkfence_types.go
config/crd/bases/csiaddons.openshift.io_networkfences.yaml
controllers/networkfence_controller.go

This PR fixes the following bugs in NetworkFence:
1. Due to incorrect implementation of markers, the additional columns were not getting displayed. 
This is now updated to show all the intended columns.
Old :
```
[yuggupta@fedora kubernetes-csi-addons]$ kubectl get networkfence
NAME                         AGE
networkfence-sample          3d17h
```
New:
```
[yuggupta@fedora kubernetes-csi-addons]$ kubectl get networkfences
NAME                         DRIVER                       CIDRS                                AGE     RESULT
networkfence-sample          rook-ceph.rbd.csi.ceph.com   ["192.2.3.1/32","88.168.23.45/32"]   3d20h   Succeeded
```
2. The correct status of Networkfence CR was not getting updated after a successful operation. Added a commit to fix the same.

Bug fixes for NetworkFence

---

controllers/csiaddonsnode_controller.go

The correct status of csiaddonsnode CR was not
getting updated.
This commit fixes the issue.
See: https://github.com/csi-addons/kubernetes-csi-addons/pull/75#discussion_r785646113
Signed-off-by: Yug Gupta <yuggupta27@gmail.com>

csiaddonsnode: update csiaddonsnode status

---

cmd/manager/main.go
config/rbac/role.yaml
controllers/reclaimspacejob_controller.go
controllers/reclaimspacejob_controller_test.go
go.mod

This commit adds ReclaimSpaceJob controller code
and unit tests for the same.
ReclaimSpaceJob controller watches for ReclaimSpaceJob,
validates resource, finds connections, makes respective
grpc requests and updates the status.

controller: add ReclaimSpaceJob controller

---

Makefile
config/manifests/bases/csi-addons.clusterserviceversion.yaml

When a release is made, the git-tag is used for the version of the
container-images. It seems that ODF-Operator assumes the tag of the
container-image matches what is used as a version of the bundle/CSV.
There is no hard requirement that these versions are the same, it is
just an assumption of ODF-Operator. However, it is the first operator
that deploys CSI-Addons, and changing the operator seems more complex
than versioning csi-addons differently.
The default version in csi-addons.clusterserviceversion.yaml has now
been set to 0.1.1, the latest git-tag that was published.
Fixes: #82

build: version the bundle/CSV the same as the tag of the container-images

---

controllers/reclaimspacejob_controller.go
controllers/reclaimspacejob_controller_test.go

Status.Condition[*].Reason is a required field
and it needs a camelCase string to be given.
If not given, object Update will fail.
```
1.6424997219990551e+09  ERROR   controller.reclaimspacejob      Failed to update status {"reconciler group": "csiaddons.openshift.io", "reconciler kind": "ReclaimSpaceJob", "name": "reclaimspacejob-sample", "namespace": "rook-ceph", "PVCName": "rbd-1", "PVCNamespace": "rook-ceph", "error": "ReclaimSpaceJob.csiaddons.openshift.io \"reclaimspacejob-sample\" is invalid: status.conditions.reason: Invalid value: \"\": status.conditions.reason in body should be at least 1 chars long"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile …
```

controller: fix reclaimspacejob reason bug

---

Makefile

By setting PACKAGE_NAME as an variable for the `make generate bundle`
command, the default "csi-addons" name can be adjusted. This is useful
to prevent conflicts while installing the component, specially when
products want to include their tested version of the CSI-Addons bundle.

build: make the CSV package-name configurable

---

PROJECT
cmd/manager/main.go
config/rbac/role.yaml
controllers/reclaimspacecronjob_controller.go
controllers/reclaimspacecronjob_controller_test.go
go.mod
go.sum
vendor/github.com/robfig/cron/v3/.gitignore
vendor/github.com/robfig/cron/v3/.travis.yml
vendor/github.com/robfig/cron/v3/LICENSE
vendor/github.com/robfig/cron/v3/README.md
vendor/github.com/robfig/cron/v3/chain.go
vendor/github.com/robfig/cron/v3/constantdelay.go
vendor/github.com/robfig/cron/v3/cron.go
vendor/github.com/robfig/cron/v3/doc.go
vendor/github.com/robfig/cron/v3/logger.go
vendor/github.com/robfig/cron/v3/option.go
vendor/github.com/robfig/cron/v3/parser.go
vendor/github.com/robfig/cron/v3/spec.go
vendor/modules.txt

This commit adds ReclaimSpaceCronJob controller code
and unit tests for the same.
ReclaimSpaceCronJob controller watches for ReclaimSpaceCronJob,
validates resource, parses given schedule, create reclaimspacejob
as per shedule, deletes old failed/successful reclaimspacejob
and updates the status.
Inspired from
- https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ 
- https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go

controller: add ReclaimSpaceCronJob controller

---

Makefile
config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml

By setting RBAC_PROXY_IMG to a different container-image, new versions
of the kube-rbac-proxy can easily be tested. Products that include
CSI-Addons may want to provide a different location of the
container-image.
Depends-on: #86

build: make kube-rbac-proxy container-image configurable

---

.github/workflows/build-push.yaml
.github/workflows/test-build.yaml
docs/ci.md

Document the GitHub Environment variable `BUILD_PLATFORMS` that is now
used in the jobs that test building container-images.

ci: limit the platforms that are build

---

Makefile

In case the *_IMG variables can contain a full qualified container-image
resource (includes a ":"), the container-images should not use the TAG
valued. The :TAG option will only be added if no predefined version is
passed.

build: enable inclusion of differently versioned container-images in the bundle

---

Makefile
config/manifests/bases/clusterserviceversion.yaml.in
config/manifests/kustomization.yaml

When PACKAGE_NAME is set while building the bundle, the base for the
clusterserviceversion manifest is not detected correctly. When that
happens, operator-sdk generates a new clusterserviceversion manifest
with default values.
Because the values in the clusterserviceversion manifest have a meaning,
and were tested with different deployments, a default new manifest is
not what we want included in the bundle.
By replacing the @PACKAGE_NAME@ placeholder in the
clusterserviceversion.yaml.in file before generating the bundle, the
resulting bundle now contains all the values from the base manifest,
with the correct package name.
This can be verified by running commands like:
- make bundle PACKAGE_NAME=hello-world
- make bundle PACKAGE_NAME=hello-world TAG=v0.0.1-alpha.42

build: generate a clusterserviceversion manifest with PACKAGE_NAME

---

internal/sidecar/service/reclaimspace.go
sidecar/main.go

error: 
```
0121 04:58:01.040729   47272 utils.go:191] ID: 1792 GRPC call: /reclaimspace.ReclaimSpaceNode/NodeReclaimSpace
I0121 04:58:01.041711   47272 utils.go:195] ID: 1792 GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e1ba208a-00e7-438c-9b98-ff9ea9ed981f/globalmount","volume_capability":{"AccessType":null,"access_mode":{"mode":7}},"volume_id":"0001-0009-rook-ceph-0000000000000005-782366e2-7a76-11ec-946e-0242ac110003"}
I0121 04:58:01.053334   47272 cephcmds.go:56] ID: 1792 an error (exit status 1) occurred while running fstrim args: [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e1ba208a-00e7-438c-9b98-ff9ea9ed981f/globalmount/0001-0009-rook-ceph-0000000000000005-782366e2-7a76-11ec-946e-0242ac110003]
E0121 …
```

sidecar/reclaimspace: fix staging path and volCaps for raw block pvc

---

PROJECT
cmd/manager/main.go
config/rbac/role.yaml
controllers/persistentvolumeclaim_controller.go
controllers/persistentvolumeclaim_controller_test.go
controllers/suite_test.go
docs/reclaimspace.md

This controller watches for annotation on PVC,
if matches with `reclaimspace.csiaddons.openshift.io/schedule`
which can specify a schedule, a reclaimspace cron job cr
is created for that PVC witha  generated name having pvc-name
as prefix.
```
Reconciles only if create or update happens to `reclaimspace.csiaddons.openshift.io/schedule: "@everyday"` annotation
steps: 
- delete all old child jobs
- check annotation for schedule
- if not found, clear name annotation if it exists and  exit
- if found, continue
- generate unique name = pvc.name+time.Now().Unix()  (ex rbd-pvc-1642598479)
- construct rscronjob
- set controllerref, create rscronjob
- exit
```

controller: add PersistentVolumeClaimController

---

config/rbac/role.yaml
controllers/persistentvolumeclaim_controller.go

Running pvc annotation controller on openshift throws the
following error.
```
"reclaimspacecronjobs.csiaddons.openshift.io \"pvcrbd10-1643271677\"
is forbidden: cannot set blockOwnerDeletion if an ownerReference refers
to a resource you can't set finalizers on: , <nil>"
```
Adding pvc finalizer rbac solves this issue.
Refer: https://bugzilla.redhat.com/show_bug.cgi?id=2046677
Similar issues https://github.com/spotahome/redis-operator/issues/98#issue-367689551

controller: add pvc finalizer rbac for annotation controller

---

controllers/reclaimspacejob_controller.go
controllers/reclaimspacejob_controller_test.go

Node reclaimspace request should not be made
when nodeID is empty indicating the pvc is
not mounted to any pod and no volumeattachment
object for that PVC was found.

controller/reclaimspacejob: skip making node req if nodeID is empty

---

Makefile
deploy/controller/setup-controller.yaml

this commit adds raw yaml generated using kustomize
in deploy/crds.yaml which can be used by others to
directly deploy the controller
Fixes: #105

controller: adds yaml to install and deploy controller

---

Makefile
config/default/kustomization.yaml

` cd config/manager && $(KUSTOMIZE) edit set image
controller=${CONTROLLER_IMG} $(KUSTOMIZE_RBAC_PROXY)`
The above command did not set rbax-proxy image since this
image variable was part of config/default/kustomization.yaml.
This commit fixes this issue and does some cleanup in the Makefile
and config/default/kustomization.yaml(running the cmd moved
/removed some default parameters).
Currently 
```
[rakshith@fedora kubernetes-csi-addons]$ RBAC_PROXY_IMG=gcr.io/kubebuilder/kube-rbac-proxy:v0.9.0 make manifests 
make: go: Permission denied
go build -o /home/rakshith/workspace/src/github.com/csi-addons/kubernetes-csi-addons/bin/controller-gen ./vendor/sigs.k8s.io/controller-tools/cmd/controller-gen
go build -o …
```

deploy: fix setting rbac-proxy image in kustomize files

---

.github/workflows/tag-release.yaml

When a tag is pushed into the repository, a release is now automatically
made from the tag. The release includes generated YAML files that can be
applied with `kubectl` to install the controller and CRDs.
Fixes: #107
See-also: https://github.com/ncipollo/release-action/

build: add a job to publish a release by tag

---

controllers/reclaimspacejob_controller.go

When a CSI-driver does not implement NodeReclaimSpace and/or
ControllerReclaimSpace, it should not reported as an error.

reclaimspace: do not report Unimplemented as an error

---

config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/namespace.yaml
deploy/controller/rbac.yaml
deploy/controller/setup-controller.yaml

csi-addon operator is using the default label and labelSelector provided by operator-sdk `control-plane: controller-manager` for its resources, this is a generic label and it can cause problems when multiple resources use the same labels changing the label to unique one.

use a unique label for csi-addons resources

---

README.md

This commit updates README with another way to deploy
the controller which is "using the yamls file"

doc: add doc for versioned deployment

---

README.md

Added badges for:
- latest released version
- Go Report Card from https://goreportcard.com
- tickgit for TODOs from https://www.tickgit.com
Also updated the 1st paragraph of the document, added a reference to the
CSI-Addons community website.
Fixes: #126

doc: include badges in the README

---

README.md
docs/deploy-controller.md

This commit removes the installations methods of CSI-Addons
controller from the README file to deploy-controller.md inside
the docs folder. This will keep the README clean and have all
documentation at one place.

cleanup: removes the docs from README to docs folder

---

config/manifests/bases/clusterserviceversion.yaml.in

Currently the CSV points to the GitHub organization, but there is a
(minimal) website at https://csi-addons.github.io which should be the
main entry point for users.

csv: use "csi-addons.github.io" for main website

---

.github/mergify.yml
.github/workflows/kind-deploy.yaml

Add a new GitHub workflow to test the deployment of the controller.

ci: add an initial job for deploying the controller

---

Makefile
config/manifests/bases/clusterserviceversion.yaml.in

Each CSV has a replaces parameter that indicates
which Operator it replaces. This builds a graph of
CSVs that can be queried by OLM, and updates can be
shared between channels. Channels can be thought of
as entry points into the graph of updates:
REPLACES ?= ""
Creating the New CatalogSource requires publishing CSVs
that replace one Operator, but can skip several. This can
be accomplished using the skipRange annotation:
SKIP_RANGE ?= ""
Refer: https://github.com/red-hat-storage/odf-operator/commit/e1c41bee0b26731a923eb06f5fc3e047539bfd6a
cc @nixpanic @Madhu-1 @iamniting

ci: add ability to have replaces,skips in CSV

---

Makefile

For the generated base csv to work, quote needs to be added
around replaces and skip_range values.
cc @Madhu-1 @nixpanic @yati1998

ci: add quotes while executing sed for replace & skip range

---

.github/dependabot.yml

Dependabot can update GitHub Actions in the workflows. It is useful to have them updated regularly so that enhancements and bugfixes get included.

ci: update GitHub Actions with Depandabot

---

config/rbac/role.yaml
controllers/csiaddons/csiaddonsnode_controller.go
controllers/csiaddons/csiaddonsnode_controller_test.go
deploy/controller/rbac.yaml
docs/csiaddonsnode.md
sidecar/internal/server/server.go
sidecar/internal/util/util.go
sidecar/main.go

When there is no `controller-ip` parameter set, the endpoint in the
CSIAddonsNode CR will be set to `pod://<name>.<namespace>:<port>`. The
Controller can then get the PodIP through the Kubernetes API. This makes
sure that the CSIAddonsNode does not need to be updated when the
IP-address of the Pod hosting the sidecar changes.
Closes: #186

Use `pod://` URL formatting for CSIAddonsNode endpoints

---

cmd/manager/main.go
controllers/csiaddons/csiaddonsnode_controller.go
controllers/csiaddons/networkfence_controller.go
controllers/csiaddons/persistentvolumeclaim_controller.go
controllers/csiaddons/reclaimspacecronjob_controller.go
controllers/csiaddons/reclaimspacejob_controller.go
docs/deploy-controller.md

Current MaxConcurrentReconciles is 1, which is the default, meaning only one request will be processed at a time. This is not useful when we have 100/1000 CR to reconcile, which can affect the performance. This PR provides a way to set the MaxConcurrentReconciles to the user's desired value so that the user can tune the configuration based on the requirement.
Note:- Currently we have performance issue in DR VolRep because of this one, the failover and failback time are slightly affected because of the default value. with this, things will be better and same change need to be done when we add VolRep Reconciler also.

provide option to set MaxConcurrentReconciles

---

cmd/manager/main.go
go.mod

Use ISO 8601 for better timestamp readability from logs.
we can also use kubectl logs --timestamps=true options for the timestamp.
Ref: https://github.com/RamenDR/ramen/pull/499
fixes #198 
```
./bin/manager
1.6612317914296057e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
I0823 10:46:32.570418 1458419 request.go:601] Waited for 1.049527477s due to client-side throttling, not priority and fairness, request: GET:https://192.168.39.26:8443/apis/policy/v1?timeout=32s
1.661231793128033e+09	ERROR	setup	unable to create controller	{"controller": "ReclaimSpaceCronJob", "error": "no matches for kind \"ReclaimSpaceJob\" in version \"csiaddons.openshift.io/v1alpha1\""}
main.main
/home/mrajanna/workspace/src/github.com/csi-addons/kubernetes-csi-addons/cmd/m …
```

controllers: Use ISO 8601 timestamp format in logs

---

apis/replication.storage/v1alpha1/volumereplication_types.go
controllers/replication.storage/pvc.go
controllers/replication.storage/pvc_test.go
controllers/replication.storage/volumereplication_controller.go

VolumeReplication should ensure there is only one VR per PVC, as otherwise, it can lead to orchestrating the
PVC is based on multiple VRs to an inconsistent state. With this Patch only one VR will operate on a single PVC.

Ensure only one VR per PVC

---

controllers/replication.storage/pvc.go
controllers/replication.storage/pvc_test.go
controllers/replication.storage/volumereplication_controller.go

As part of #213, support was added to have one VR per PVC. Once the VR is deleted, we need to remove the annotation so a new VR can be created for the same PVC. This PR adds the missing piece.

replication: remove annotation from pvc

---

.github/workflows/tag-release.yaml

failed workflow https://github.com/csi-addons/kubernetes-csi-addons/runs/8089285012?check_suite_focus=true

rebase: use go 1.18 in tag-release workflow

---

controllers/csiaddons/csiaddonsnode_controller.go

resolveEndpoint get the pod object to resolve the ip address as the pod object is deleted resolveEndpoint will fail to get the pod and it blocks the csiaddonsnodes object from getting deleted because of this logs will get flooded and other csiaddons operation might also fail.
To fix this problem call resolveEndpoint only if the csiaddonsnodes object is not deleted.

controller: fix csiaddonsnodes object deletion

---

controllers/csiaddons/reclaimspacejob_controller.go

add nodeID to error message to provide more details for debugging.

relcaimspace: add nodeID to error message

---

controllers/replication.storage/volumereplication_controller.go
go.mod
go.sum
vendor/modules.txt

LastSyncTime can be optional and nil also, there is no strict check for it, and if we dont have this check the [default UNIX time](https://go.dev/play/p/81CmSxr-r8S) will get added to the CR, which doesn't make sense. If the time is not present keep the last known LastSyncTime itself.
Depends-On: csi-addons/spec#47

replication: update LastSyncTime if its not nill

---

controllers/replication.storage/volumereplication_controller.go
controllers/replication.storage/volumereplication_test.go
docs/volumereplicationclass.md

Reduce the schedule time by half to get the latest update and also to avoid the inconsistency between the last sync time in
the VR and the Storage system.
The user can see updates for RPO that are not stuck in a bad schedule race, i.e, VolumeReplication checks and finds sync time as t-5m, and just after that storage system updates it to t+x. If we checked every 1/2 of the schedule we will update it to t+x in t+s/2

replication: reduce the reqeue time for GetReplicationInfo

---

PROJECT
apis/replication.storage/v1alpha1/volumereplication_webhook.go
apis/replication.storage/v1alpha1/webhook_suite_test.go
cmd/manager/main.go
config/webhook/manifests.yaml
deploy/controller/install-all-in-one.yaml

Add webhook for volume replication object to prevent users from changing the dataSource or the volumeReplicationClass once created. Below is the command to generate a webhook for VolumeReplication object
```bash
$ operator-sdk create webhook --group replication.storage --version v1alpha1 --kind VolumeReplication --programmatic-validation
```

webhook: add webhooks for volumereplication

---

.github/workflows/kind-deploy.yaml

When passing `platforms:` to the docker-build-push GitHub Action, QEMU needs to be configured and the `docker-buildx` action needs to be used. For the Kind deployment test, there is no need to run it on different platforms.

ci: only build container for Kind GitHub Action on current platform

---

controllers/replication.storage/volumereplication_controller.go

Avoid extra RPC calls as request will be requested again for updating the LastSyncTime in the status. The image need to be promoted only one time not always during the reconcile.
fixes: #250
Co-authored-by: Madhu Rajanna <madhupr007@gmail.com>

replication: reduce RPC calls when VR state is primary

---

controllers/csiaddons/reclaimspacejob_controller.go

This commit makes modification to ignore Volume Attachment objects which are being deleted or not attached.

reclaimspace: consider VA object only it is attached & not being deleted

---

apis/csiaddons/v1alpha1/csiaddonsnode_types.go
apis/csiaddons/v1alpha1/networkfence_types.go
apis/csiaddons/v1alpha1/reclaimspacecronjob_types.go
apis/csiaddons/v1alpha1/reclaimspacejob_types.go
apis/replication.storage/v1alpha1/volumereplication_types.go
apis/replication.storage/v1alpha1/volumereplicationclass_types.go
config/crd/bases/csiaddons.openshift.io_csiaddonsnodes.yaml
config/crd/bases/csiaddons.openshift.io_networkfences.yaml
config/crd/bases/csiaddons.openshift.io_reclaimspacecronjobs.yaml
config/crd/bases/csiaddons.openshift.io_reclaimspacejobs.yaml
config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
deploy/controller/crds.yaml
deploy/controller/install-all-in-one.yaml

All the CRs need to have valid spec field,
therefore this commit marks .spec field of all CRs as required using kubebuilder validation tag.

api: mark spec field of CRs as required

---

config/crd/kustomization.yaml
config/manifests/bases/clusterserviceversion.yaml.in
deploy/controller/crds.yaml
deploy/controller/install-all-in-one.yaml

We currently don't have a conversion webhook,
therefore can support the OwnNamespace installMode type too.
This change was done by default when webhook support was added.

build: support OwnNamespace installMode type

---

internal/sidecar/service/volumereplication.go

use the correct operation type when logging.

replication: correct log message

---

controllers/replication.storage/volumereplication_controller.go
internal/util/error.go
internal/util/error_test.go

This commit adds code to handle UnimplmentedError from getVolumeReplicationInfo rpc. The controller wil now ignore this error and not requeue the request.
Fixes: #236

controller/replication: add UnimplementedError for getVolRepInfo()

---

controllers/replication.storage/volumereplication_controller.go

A bug was introduced in 90f59d1f due to which
Volumereplication controller always gave error.
This commit fixes the same.

controller/replication: fix bug in Unimplmented error check

---

apis/replication.storage/v1alpha1/volumereplication_types.go
config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
deploy/controller/crds.yaml
deploy/controller/install-all-in-one.yaml

Currently, if a user will want to create `VolumeReplication` without the `autoResync` field it will fail because it’s a required field. After this PR it will have a default in the CRD and it won’t fail and will create the object with the default value

add default value to autoResync

---

README.md
config/manager/manager.yaml
deploy/controller/install-all-in-one.yaml
deploy/controller/setup-controller.yaml
docs/deploy-controller.md

We now have 100 workers by default and watch a lot of resources such as PVCs,  VolumeAttachments and owned CRs. This leads to Out-Of-Memory kills(OOMKILLs) with just limit of 128Mi.
Therefore, raising limit to 512Mi memory and 1000m cpu./
> Note: I am noticing increase of 50Mi usage with 1000 PVC with reclaimspace annotation. This new limit should give us headroom, while the requested resource is still the same.

build: increase default resource cpu & memory limits

---

apis/csiaddons/v1alpha1/networkfence_webhook.go

When a NetworkFence CR is validated, an incorrect comparison is done. `DeepEqual()` returns `true` when the there are no changes, this is valid and not an error. Adding `!` to inverse the check corrects the comparison and only reports an error when the parameters are modified.
See-also: https://bugzilla.redhat.com/2182375

NetworkFence: correct check in validating webhook

---

cmd/manager/main.go
config/rbac/role.yaml
controllers/csiaddons/persistentvolumeclaim_controller.go
controllers/csiaddons/persistentvolumeclaim_controller_test.go
deploy/controller/install-all-in-one.yaml
deploy/controller/rbac.yaml
docs/reclaimspace.md

Currently, we only support the reclaimspace feature on the PVC annotation. However, this adds support for namespace annotations as well. If the required PVC annotation is missing, our controller will check if the necessary annotation is present on the namespace. If it is, the scheduling details will be retrieved from the namespace annotation and used to create the ReclaimspaceCronJob.
It's important to note that the PVC annotation will take precedence over namespace annotations.
Please be aware that we can only create a reclaimspaceCronJob if the annotation exists on the namespace. If an admin wants to update or remove the annotation on the namespace, the same action must be taken on all the PVCs within that namespace.

reclaimspace: add support for namespace annotation

---

.github/workflows/golangci-lint.yaml
Makefile
apis/csiaddons/v1alpha1/reclaimspacecronjob_webhook.go
cmd/csi-addons/main.go
controllers/csiaddons/persistentvolumeclaim_controller.go
controllers/csiaddons/reclaimspacecronjob_controller.go
controllers/csiaddons/suite_test.go
internal/connection/connection.go
sidecar/internal/csiaddonsnode/csiaddonsnode.go

Based on the example in the golangci-lint GitHub Action documentnation.
**Note:** this PR is a _draft_ until there are no linter issues reported anymore.

ci: add GitHub Workflow for golangci-lint

---

.github/workflows/build-push.yaml
.github/workflows/kind-deploy.yaml
.github/workflows/tag-release.yaml
.github/workflows/test-build.yaml
.github/workflows/test-golang.yaml
go.mod

In preparation for updating the Kubernetes dependencies to v1.27 or newer, start using Go 1.20 now already.

build: use Go 1.20 as Kubernetes packages require that too

---

cmd/manager/main.go
config/manager/manager.yaml
config/manager/manager_auth_proxy_patch.yaml
deploy/controller/csi-addons-config.yaml
deploy/controller/install-all-in-one.yaml
deploy/controller/setup-controller.yaml
docs/csi-addons-config.md
docs/deploy-controller.md
internal/util/config.go
internal/util/config_test.go

This commits adds support for configuration options consumed through a optional configmap. This will enable users to create a configmap to supply options that are persisted throughout upgrades.
Current support parameters are `"reclaim-space-timeout"` and `"max-concurrent-reconciles"`.
Closes: #347

controller: add support for global persistent configuration

---

controllers/csiaddons/reclaimspacecronjob_controller.go

The reclaimspacecronjob may miss too many runs due to the following reasons:
- low startingDeadlineSeconds
- clock skew
- (added now) when user has reduced schedule which in turn leads to the new interval being < 100 times of old interval, aka >100 missed runs.
This issue only occurs when user changes schedule which drastically reduces interval by more than 100 times. Error message is improved to ask user to delete and recreate cronjob to overcome this issue.

controller: improve error for missed start times in cronjob

---

Makefile
build/Containerfile.tools

It seems that not all developers use an updated version of Fedora. For the contributors that need to update `*.proto` files and re-generate the related `*.pb.go` files, the new `make docker-generate-protobuf` command will be very useful.

build: add `make docker-generate-protobuf` to update genedated `*.pb.go` files

---

Makefile

With recent changes to detect Podman/Docker, the
`docker-generate-protobuf` make target was broken. The parameters to the container build command were passed like `$^`, and not only the Containerfile filename.
Fixes: #372

build: fix `make docker-generate-protobuf` target

---

Dockerfile
build/Containerfile.sidecar

This also moves to use the quay.io mirror of the Golang container-image from docker.io. Docker Hub has pull restrictions, that can prevent pulling the image if it is done too often. Quay.io does not enforce restrictions like that.

build: use Go 1.20 while building in container

---

.github/dependabot.yml

The `/tools` directory was added with commit 342d457093cccd. It is needed to update the dependencies of the tools separately.

ci: include `/tools` directory in dependabot config

---

Makefile
cmd/manager/main.go
internal/version/version.go
sidecar/main.go

Fixes https://github.com/csi-addons/kubernetes-csi-addons/issues/377
Fixes https://github.com/csi-addons/kubernetes-csi-addons/issues/378
The output will be printed as:
Version: v0.6.0
Git Commit: 43ebc4baac5f8893a7d061bab9db78f66640b6b8
Go Version: go1.19.9
Compiler: gc
Platform: linux/amd64

Adding version details to sidecar

---

Dockerfile
build/Containerfile.sidecar

This commit switches back to docker for
base image golang:1.20 since github actions
does not seem to be able to pull from quay
intermittently.
The actions seem to be failing from around the same time this change was introduced.
https://github.com/csi-addons/kubernetes-csi-addons/pull/383/files
https://github.com/csi-addons/kubernetes-csi-addons/actions/workflows/build-push.yaml
We can further investigate and revert this after the release.

build: switch back to docker for golang:1.20

---

controllers/csiaddons/persistentvolumeclaim_controller.go

Logic used for determining reclaimspace annotation based on ns annotation and driver support had a bug which caused all the PVCs regardless of driversupport being annotated.
This commit makes sure only pvc with driver which
support reclaimspace is annotated/ requeued.

controller: fix reclaimspace based on ns annotation

---

.github/workflows/lint-extras.yaml
docs/deploy-controller.md
docs/volumereplication.md

add lint-extras github workflow

ci: add lint-extras github workflow

---

.github/workflows/tag-release.yaml

The release is created a little before images are pushed. This caused some confusion by consumers who were very eager to adopt the new version. By having the release job depend on the image building and pushing, this should not happen anymore.

ci: wait for images to be pushed before creating the release

---

.github/workflows/lint-extras.yaml
CONTRIBUTING.md
README.md
cmd/csi-addons/README.md
docs/csiaddonsnode.md
docs/networkfence.md
docs/reclaimspace.md

This PR involves enabling of Markdown linter and fixing the failures.
Updates: https://github.com/csi-addons/kubernetes-csi-addons/issues/405, https://github.com/csi-addons/kubernetes-csi-addons/issues/12

fix: fix markdown failures

---

cmd/csi-addons/README.md
cmd/csi-addons/main.go
cmd/csi-addons/networkfence.go
cmd/csi-addons/networkfence_test.go

Adding the missing NetworkFence capability to the
cmd/csi-addons admin/test tool.
Fixes: #204

test: Adding NetworkFence capability to test tool

---

cmd/csi-addons/README.md
cmd/csi-addons/replication.go

Adds the testing tool for replication
[riyasinghal@fedora ceph-csi]$ kubectl exec -c csi-addons csi-rbdplugin-provisioner-66c68cd59b-4gvn8 -n rook-ceph -- csi-addons -operation EnableVolumeReplication -clusterid rook-ceph --secret default/csi-rbd-secret -endpoint unix:///csi/csi-addons.sock -volumeID 0001-0009-rook-ceph-0000000000000002-deda762a-2910-47fa-9dfe-4b492f719ca7
Enable Volume Replication operation successful
[riyasinghal@fedora ceph-csi]$ kubectl exec -c csi-addons csi-rbdplugin-provisioner-66c68cd59b-4gvn8 -n rook-ceph -- csi-addons -operation DisableVolumeReplication -clusterid rook-ceph --secret default/csi-rbd-secret -endpoint unix:///csi/csi-addons.sock -volumeID 0001-0009-rook-ceph-0000000000000002-deda762a-2910-47fa-9dfe-4b492f719ca7
Disable Volume Replication operation …

cmd: add testing tool for volume replication

---

apis/csiaddons/v1alpha1/networkfence_types.go
apis/replication.storage/v1alpha1/volumereplicationclass_types.go
config/crd/bases/csiaddons.openshift.io_networkfences.yaml
config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
deploy/controller/crds.yaml

With current code we cannot update the parameters/secret once created but Currently we have a bug in spec where secrets/parameters can be deleted once created but we should not allow that operation as well. This PR contains the fix which doesn't allow the deletion of parameters/secrets once created.

Fix corner cases bugs found in CEL validation

---

internal/connection/connection.go

The idle timeout was disabled, but has been enabled by default in
google.golang.org/grpc v1.59. The kubernetes-csi-addons operator acts
similarly to the Kubernetes external-provisioner, and benefits from
having a functional gRPC connection open to the csi-addons sidecars that
run alongside CSI-drivers.
See-also: kubernetes-csi/external-provisioner#1099

Explicitly disable gRPC idle timeout

---

controllers/csiaddons/csiaddonsnode_controller.go
controllers/csiaddons/networkfence_controller.go
internal/connection/connection.go
internal/connection/connection_pool.go
internal/util/normalize.go
internal/util/normalize_test.go
sidecar/internal/client/client.go
sidecar/internal/csiaddonsnode/csiaddonsnode_test.go
sidecar/main.go
vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
vendor/modules.txt

- util: add `NormalizeLeaseName()`
- sidecar: use leader election when CONTROLLER_SERVICE is supported
- controller: send NetworkFence requests to the leading CSI-Addons sidecar
Resolves: #422

send NetworkFence requests to the leading CSI-Addons sidecar

---

Makefile
config/rbac/role.yaml
controllers/csiaddons/csiaddonsnode_controller.go
deploy/controller/rbac.yaml
internal/connection/connection.go
internal/connection/connection_pool.go

The CSIAddonsNode objects are located in the Namespace where CSI-drivers are running. Use this Namespace in the Connection struct, so that the Lease for a group of CSI-Addons ControllerServers can be found.
Updates: #422

connection: track Namespace of driver Pods to locate Leases

---

cmd/manager/main.go

Adding the following options:
```
-leader-election-lease-duration duration
Duration, in seconds, that non-leader candidates will wait to
force acquire leadership. Defaults to 15 seconds. (default 15s)
-leader-election-renew-deadline duration
Duration, in seconds, that the acting leader will retry
refreshing leadership before giving up. Defaults to 10 seconds.
(default 10s)
-leader-election-retry-period duration
Duration, in seconds, the LeaderElector clients should wait
between tries of actions. Defaults to 5 seconds. (default 5s)
```
Some container platforms (like OpenShift) have recommendations for these
timeout that differ from the Kubernetes defaults. With these options,
deployments can define the timeouts according to their own preferences.

manager: make leader election timeouts configurable

---

controllers/csiaddons/reclaimspacecronjob_controller.go
controllers/csiaddons/reclaimspacecronjob_controller_test.go

Adding unit test for getNextSchedule function in the reclaimspacecronjob_controller.

test: unit test for getNextSchedule

---

config/manager/manager.yaml
config/manager/manager_auth_proxy_patch.yaml
deploy/controller/setup-controller.yaml

Prevent potential abuse of the container storage a little more, by
running all containers with a read-only filesystem.

deploy: run all containers with read-only filesystem

---

controllers/csiaddons/csiaddonsnode_controller.go
controllers/csiaddons/networkfence_controller.go
controllers/csiaddons/persistentvolumeclaim_controller.go
controllers/replication.storage/finalizers.go
controllers/replication.storage/volumereplication_controller.go
internal/util/strings.go
internal/util/strings_test.go

With Go 1.21 the "slices" package can be used for many operations on slices. The custom ContainsInSlice() function can be replaced by the standard slices.Contains().

replace custom ContainsInSlice() with standard slices.Contains()

---

go.mod
tools/go.mod

some CI/developers will not have flexibility  to switch to the latest version, we are sticking to the first release version of golang 1.22

ci: use golang 1.22.0 for main build

---

config/rbac/role.yaml
controllers/csiaddons/persistentvolumeclaim_controller.go
deploy/controller/rbac.yaml
docs/reclaimspace.md

This commit adds support for auto ReclaimSpace by StorageClass annotations. 
For newly created PVCs ReclaimSpaceCronjob will be created for PVCs associated
with a StorageClass that has the ReclaimSpace annotation.

reclaimspace: support for storageclass annotation

---

apis/replication.storage/v1alpha1/volumegroupreplication_types.go
config/crd/bases/replication.storage.openshift.io_volumegroupreplications.yaml
deploy/controller/crds.yaml

we need to have a VRC name to create the VR, this PR adds a new field to the VGR to pass down the VRC name for the VolumeReplication object.

replication: add missing VRC name for VGR

---

.github/mergify.yml

This PR updates the Mergify rules with the below changes:
- adds the DNM (Do Not Merge) label to PR that have `DNM` in their title.
- Prevents the automatic merging of PR with the DNM label, even if they have more than two approvals.
closes: #595

ci: add DNM label rules for mergify

---

controllers/csiaddons/persistentvolumeclaim_controller.go
controllers/csiaddons/persistentvolumeclaim_controller_test.go

In my earlier PR https://github.com/csi-addons/kubernetes-csi-addons/pull/585, I missed few changes 😞 
This commit addresses a bug in `determineScheduleAndRequeue` where the check for schedule from the StorageClass annotations is never reached.

reclaimspace: fix schedule handling

---

docs/deploy-controller.md

super-linter/textlint failed with `Incorrect term: “yaml”, use “YAML” instead  terminology`.

doc: correct case of YAML from yaml

---

internal/sidecar/service/volumereplication.go
internal/sidecar/service/volumereplication_test.go

When src is nil, we create a new instance of csiReplication.ReplicationSource but this newly created instance does not
propagate back to the caller since Go passes pointers by value, This commit fixes the problem.

replication: fix problem with setReplication

---

docs/encryptionkeyrotation.md

This PR adds the documentation for EncryptionKeyRotation(Cron)Job CRs.

docs: add documentation for EncryptionKeyRotation

---

internal/controller/csiaddons/persistentvolumeclaim_controller.go
internal/controller/csiaddons/persistentvolumeclaim_controller_test.go

This patch modified the PVC controller so that it
reconciles the pvcs for encryptionkeyrotation
operations.
**Note:** Please review the most recent commit only as the rest of them are unrelated to this feature. The extra commits are due to this PR being based off of impl-pvkr branch.
Depends-on: #608 
Regards

Modify pvc controller to reconcile encryptionkeyrotation

---

docs/reclaimspace.md
internal/controller/csiaddons/persistentvolumeclaim_controller.go

Currently, If annotations are set on StorageClass this will only affect new PVCs created from this StorageClass for ReclaimSpace operations. To include existing PVCs, one needs to restart the controller.
This commit eliminates the need of restarting the controller by watching the StorageClass object and Equeue all PVCs of it, this will then allow considering the existing PVCs and annotations will be set.
Initial testing - 
RBD StorageClass
```yaml
$ k get sc rook-ceph-block -oyaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
creationTimestamp: "2024-07-08T06:48:23Z"
name: rook-ceph-block
resourceVersion: "1879671"
uid: 8e8e36e4-f0fb-460c-b352-3efd8799479e
parameters:
clusterID: rook-ceph
csi.storage.k8s.io/controller-expand-secret-name: …
```

reclaimspace: enhancement to consider existing PVCs for StorageClass Annotations

---

internal/sidecar/service/reclaimspace.go

This handling is no longer necessary as Kuberenetes 1.24 is not supported anymore.
Additionally, the version comparison that was used will break on some Kubernetes versions (any SemVer with a non-integer component). Removing the check fixes this problem as well.
Closes #623

Remove special handling of targetpath for deprecated Kubernetes 1.24

---

docs/deploy-controller.md
internal/sidecar/service/encryptionkeyrotation.go

This PR updates the documentation for Installation section.

doc: update installation document

---

Makefile
config/manager/kustomization.yaml
deploy/controller/setup-controller.yaml

kube-rbac-proxy was pulled from the Google Container Registry, and
Kubernetes managed projects prefer not to use that anymore.
The container-image is (for now, still) maintained outside of the
Kubernetes project, and it is recommended to pull it from quay.io.
While validating the container-image location, it seems that there is a
new version available. Now also using the latest v0.18.0.
Updates: #643

build: update kube-rbac-proxy to v0.18.0

---

api/replication.storage/v1alpha1/volumereplication_types.go
internal/controller/replication.storage/status.go

The consumers of the Replication API expect the conditions to be something imported and comparable to the other repos. For the same reason for moving the conditions to replication
types.
fixes: #649

replication: move conditions to api

---

Dockerfile
build/Containerfile.sidecar

GitHub Actions report the following warning:
> The 'as' keyword should match the case of the 'from' keyword
> FromAsCasing: 'as' and 'FROM' keywords' casing do not match
All other container build commands are CAPITALIZED, changing 'as' to 'AS'
matches it now.
See-also: https://docs.docker.com/go/dockerfile/rule/from-as-casing/

build: address FROM/as casing warning

---

config/default/kustomization.yaml

Unnecessary prefix: csi-addons- was added by mistake in default kustomization.yaml in below commit
https://github.com/csi-addons/kubernetes-csi-addons/commit/90c23d244b198b6df9d2350bd1ab80d8e0c1d784#diff-c006b1ef995eeeb57408cce42bd84db8dfc0cbe18df03222857665cebb1ac6fd

deploy: remove extra prefix: csi-addons-

---

api/replication.storage/v1alpha1/volumereplication_types.go
internal/controller/replication.storage/status.go
internal/controller/replication.storage/volumereplication_controller.go

This commit adds new Validated condition.
This is initially used to indicate the csi driver
responded with FailedPrecondition grpc code for
EnableReplication request using
`PrerequisiteNotMet` reason.

replication: add new Validated condition

---

internal/controller/csiaddons/persistentvolumeclaim_controller.go
internal/controller/csiaddons/persistentvolumeclaim_controller_test.go

This PR refactors the PVC controller to reduce
code duplication by extracting common logic
into its own functions/packages

Refactor PVC controller

---

config/manifests/bases/clusterserviceversion.yaml.in

This PR adds the EncryptionKeyRotation and
VolumeGroupReplication CRDs to the bundle's CSV.

bundle: Add missing CRDs to bundle CSV

---

cmd/csi-addons/main.go

For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which reduces CPU consumption related to (de)serialization, reduces overall latency of the API call, reduces memory footprint, reduces the amount of work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.

Use protobuf encoding for core K8s apis

---

internal/controller/csiaddons/persistentvolumeclaim_controller.go
internal/controller/csiaddons/persistentvolumeclaim_controller_test.go

`pvc.Spec.StorageClassName` is a string pointer and can be nil or empty. This commit adds check for both nil and empty.

controller/pvc: add checks for nil/empty pvc.Spec.StorageClassName

---

.github/workflows/build-push.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/kind-deploy.yaml
.github/workflows/tag-release.yaml
.github/workflows/test-build.yaml
.github/workflows/test-golang.yaml

instead of defining own go version in test files we can use go.mod to setup the required version.

rebase: use go.mod for go version

---

go.mod

we dont have downstream golang with version 1.22.6 and csi-addons needs 1.22.6 to build for that reason we can use the toolchain to enforce the soft dependency.

rebase: use toolchain for 1.22.6

---

internal/controller/csiaddons/csiaddonsnode_controller.go
internal/controller/csiaddons/csiaddonsnode_controller_test.go

kubernetes allows us to create pod with '.' in between, we should not limit parsing such endpoints

refactor parseEndpoint to accept pod names with '.' in it

---

internal/controller/csiaddons/csiaddonsnode_controller.go
internal/controller/replication.storage/volumereplication_controller.go

The csi-addons sidecar sanitizes the holder identity. The connection pool stores the mapping with key as the unsanitized name for csiaddonsnode, which leads to the `failed to find the namespace where driver` issue. 
To address this, we should sanitize the csiaddonsnode name before entering it into connection pool.

sanitize connection pool key pod name

---

cmd/csi-addons/README.md
cmd/csi-addons/main.go
cmd/csi-addons/volumegroup.go

This commit adds testing tool for VolumeGroup operations such as-
- CreateVolumeGroup
- ModifyVolumeGroup Membership
- DeleteVolumeGroup
- ControllerGetVolumeGroup
Resolves #653 
Sample outputs for the cli commands of the form:
`kubectl exec -c csi-addons <csi-addons-nodeplugin> -n rook-ceph -- csi-addons -operation <operationName> -secret <namespace/name> -parameters <key1=value1,...>`
- CreateVolumeGroup:
`Volume Group created: volume_group:{volume_group_id:"0001-0009-rook-ceph-0000000000000002-21fb957f-7987-44f8-972c-36c6e57896b0"}`
- ModifyVolumeGroupMembership: 
`Volume Group Membership modified for- volume_group:{volume_group_id:"0001-0009-rook-ceph-0000000000000002-21fb957f-7987-44f8-972c-36c6e57896b0"}`
- DeleteVolumeGroup:
`Volume Group Deleted.`
- ControllerGetVolumeGroup: …

test: Add testing tool for VolumeGroup

---

docs/encryptionkeyrotation.md
internal/controller/csiaddons/persistentvolumeclaim_controller.go

This patch adds the option to disable the keyrotation
by annotating the storageclasses, namespaces or PVCs
with: `keyrotation.csiaddons-opneshift.io/enable: false`

Add option to disable KeyRotation

---

internal/controller/csiaddons/csiaddonsnode_controller.go
internal/controller/csiaddons/csiaddonsnode_controller_test.go

In the connection pool we store the connection with unique identifier, the pod name and the namespace is used as the key to the connection  in the pool and GetLeaderByDriver get the leader based on the driver name and uses the identity of the leader which is pod name as the key to get the connection.

Fix key in connection pool

---

docs/reclaimspace.md

This patch updates the documentation with the
steps to disable reclaim space operations.

docs: Add documentation for disabling ReclaimSpace

---

internal/controller/csiaddons/csiaddonsnode_controller.go
sidecar/internal/csiaddonsnode/csiaddonsnode.go

csi-lib-utils/leaderelection:sanitizeName() is used to sanitize the leader identity used for the leases csiaddonsnode need to store the key with same format so that it can be used to get the connection.
The pod owned by deployment might move to new nodes and this might create the stale CSIAddonsNode object on the old node if we set Deployment as the ownerRef (this could leave stale connection in connection map and a CR).
so, we need to set the pod as the owner for the deployment as we dont store any details that are required later on for any other operations like Fencing etc.

Fix key and ownerRef bug

---

.github/workflows/build-push.yaml
.github/workflows/test-build.yaml
docs/ci.md

There is not need for `secrets.BUILD_PLATFORMS`, as the platforms are
not confidential. Instead a variable has been created in the GitHub
repository settings for it now.
The `secrets.BUILD_PLATFORMS` includes linux/arm/v7, which is a slow and
phased out architecture. All reasonable ARM platforms are linux/arm64
now. Dropping the linux/arm/v7 platform makes building the container
images much faster.
Closes: #719

ci: drop linux/arm/v7 from the platforms for building container-images

---

internal/controller/csiaddons/csiaddonsnode_controller.go

The pod is set as the owner of the csiaddons node object, and when the owner pod is deleted the csiaddons need to be deleted as well, When the delete Reconciles happens we cannot get the pod deletails to resolve the endpoint and we dont
need that as well when we are deleting the CR.

csiaddons: allow deleting of the CR

---

Dockerfile
build/Containerfile.sidecar
go.mod

Latest Kubernetes packages depend on Go 1.23.0.
See-also: #728

build: require go 1.23 or newer

---

internal/kubernetes/token/grpc.go
sidecar/internal/csiaddonsnode/csiaddonsnode.go

As per https://www.ietf.org/archive/id/draft-ietf-httpbis-http2bis-02.html#section-8.1.2 lower case should be used and gRPC library is automatically converting to lower case. 
Fixes issue https://github.com/csi-addons/kubernetes-csi-addons/issues/750

Lower case should be used for HTTP/2 fields

---

cmd/csi-addons/volumegroup.go

when creating empty volume group through cli, the strings.Split() function returns a [""] value, i.e, a slice of length 1 having the value as 1 (`[""]`) empty string. As a result, the csi panics when it tries to find the volumeID with the respective value.

fix empty volume group creation through cli tool

---

sidecar/internal/csiaddonsnode/csiaddonsnode.go
sidecar/main.go

This patch adds a watcher to csi-addons sidecar which is responsible for re-creating CSIAddonNode(s) in case they
are deleted manually.
Fixes: #762

csiaddonsNode: Recreate CSIAddonsNode with active sidecar(s)

---

sidecar/internal/csiaddonsnode/csiaddonsnode.go

This patch propagates the error returned from `getCSIAddonsNode`

sidecar: Handle error correctly inside DispatchWatcher

---

api/csiaddons/v1alpha1/networkfence_types.go
config/crd/bases/csiaddons.openshift.io_networkfences.yaml
deploy/controller/crds.yaml
docs/networkfence.md
internal/controller/csiaddons/networkfence_controller.go

This patch adds support for reading the driver, secrets and
parameters from `NetworkFenceClass` if `NetworkFenceClassName` is specified 
in the spec for `NetworkFence`.

Prefer NetworkFenceClass for secrets and params

---

api/replication.storage/v1alpha1/volumegroupreplication_types.go
api/replication.storage/v1alpha1/volumegroupreplicationcontent_types.go
cmd/manager/main.go
config/rbac/role.yaml
deploy/controller/rbac.yaml
docs/volumegroupreplicationclass.md
internal/client/volumegroup-client.go
internal/controller/replication.storage/finalizers.go
internal/controller/replication.storage/parameters.go
internal/controller/replication.storage/pvc.go
internal/controller/replication.storage/pvc_test.go
internal/controller/replication.storage/utils.go
internal/controller/replication.storage/volumegroupreplication_controller.go
internal/controller/replication.storage/volumegroupreplication_test.go
internal/controller/replication.storage/volumegroupreplicationclass.go
internal/controller/replication.storage/volumegroupreplicationclass_test.go
internal/controller/replication.storage/volumegroupreplicationcontent_controller.go
internal/controller/replication.storage/volumereplication_controller.go

This PR adds the following codes/logic:
- Added volume group replication controller logic
- Added generated crds, rbacs
- Added docs to create VGR, VGRClass and VGRContent CRs

Add volume group replication controller code

---

internal/connection/connection.go
internal/connection/connection_pool.go
internal/connection/connection_pool_test.go
internal/controller/csiaddons/encryptionkeyrotationjob_controller.go
internal/controller/csiaddons/persistentvolumeclaim_controller.go
internal/controller/csiaddons/reclaimspacejob_controller.go

This patch adds support to close the lingering gRPC connections
that have not been used for a certain amount of time, default to 5 mins.
An interceptor is used to track the last access time in a reliable
manner.
If a expired connection is requested, it will first be re-created and
then returned to the caller.
Since gRPC connections are not simple disconnects but a complete
tear down, re-creating the connections is necessary.
Closes: #117

connection: Disconnect idle gRPC connections on inactivity

---

.github/mergify.yml

mergify: fix mergify config

---

internal/controller/replication.storage/pvc_test.go
internal/controller/replication.storage/volumegroupreplication_controller.go
internal/controller/replication.storage/volumegroupreplication_test.go
internal/controller/replication.storage/volumereplication_controller.go

Remove namespace name from pvc owner annotation.
Name should be enough to identify vgr/vr the pvc belongs to as the annotation key for vr and vgr is different and both are namespaced scope CRs which would belong to the same namespace as PVC.

remove namespace name from pvc owner annotation

---

PendingReleaseNotes.md
api/replication.storage/v1alpha1/volumegroupreplication_types.go
config/crd/bases/replication.storage.openshift.io_volumegroupreplications.yaml
deploy/controller/crds.yaml
docs/volumegroupreplication.md
internal/controller/replication.storage/volumegroupreplication_controller.go

add a new field named `External` which when set to `true` means the VGR won't be reconciled by csi-addons controller and instead it should be managed by the storage vendor specific controller.
Also, make VolumeReplicationClassName optional in VGR's spec such that external vendors are not tied up to VR specific implementation.

add support for agnostic storage vendor in VGR

---

config/manager/manager.yaml
deploy/controller/setup-controller.yaml

In Kubernetes, termination messages allow containers to communicate the reason for termination, which might be useful for debugging.
Unless explicitly configured, Kubernetes defaults to the following:
```
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
```
This indicates that if a container exits with an error and the `/dev/termination-log` file is empty, the termination message in the Pod status will be blank.
If `/dev/termination-log` is empty and the container exits with an error, Kubernetes will use the last few lines of the container’s logs as the termination message, thus providing information when the termination log file does not have any.

config: add terminationMessagePolicy to csi-addons

---

sidecar/internal/volume-condition/reporter.go
sidecar/main.go

Follow-up on several comments that were made in #831 for improving:
- fail when passing an unknown recorder
- log an error when recording a condition fails
- use constants for flag values for recorders

Fixups for volume condition reporter

---

internal/controller/replication.storage/status.go
internal/controller/replication.storage/volumereplication_controller.go

When a VR/VGR is demoted to secondary, we don't call the `VolumeInfo` on the volume/group anymore, so the older conditions are not updated and will show stale data. We should instead remove replicating condition from VR/VGR status when the image/group is demoted to secondary state.

remove replicating condition when state is secondary

---

api/replication.storage/v1alpha1/volumegroupreplication_types.go
api/replication.storage/v1alpha1/volumegroupreplicationclass_types.go
api/replication.storage/v1alpha1/volumegroupreplicationcontent_types.go
api/replication.storage/v1alpha1/volumereplication_types.go
api/replication.storage/v1alpha1/volumereplicationclass_types.go
config/crd/bases/replication.storage.openshift.io_volumegroupreplicationclasses.yaml
config/crd/bases/replication.storage.openshift.io_volumegroupreplicationcontents.yaml
config/crd/bases/replication.storage.openshift.io_volumegroupreplications.yaml
config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
deploy/controller/crds.yaml

```
VolumeReplication now supports VolumeGroupReplication as a data source.
However, running 'kubectl get volumereplication' still displays a PVCNAME
column, which becomes misleading when the data source is a
VolumeGroupReplication.
This commit removes the PVCNAME column and introduces two new columns:
SOURCEKIND and SOURCENAME, which accurately reflect the source
information.
Also, adds additional column 'Age' for VolumeReplicationClass.
```
```
Adds shortNames for VolumeGroup related CRDs as below:
- VolumeGroupReplication: vgr
- VolumeGroupReplicationContent: vgrcontent
- VolumeGroupReplicatonClass: vgrc
Also, add additional printColumns to VolumeGroup CRDs as below:
- VolumeGroupReplication: className, contentName, desiredState, currentState, age
- VolumeGroupReplictionContent: …
```

fix: crds shortnames and printcolumns
