api/v1alpha1/csiaddonsnode_types.go, docs/csiaddonsnode.md
This commit changes v1beta1 version to
v1alpha1
=> change v1 from beta to alpha

.github/mergify.yml, .github/workflows/codespell.yml, CONTRIBUTING.md
Adds codespell github actions
Updates: #12
=> ci: add codespell

go.mod, sidecar/internal/service/reclaimspace.go, sidecar/main.go
This commit adds reclaimspace service setup.
The implementation will be done in a follow-up
pr.
=> sidecar: add reclaimspace service setup

.github/dependabot.yml
Add Dependabot for automatically creating updates to go.mod and the
vendor/ directory.
=> ci: add Dependabot configuration

.github/mergify.yml, .github/workflows/test-build.yaml
Refer: https://docs.mergify.com/conditions/#github-actions
check summary here 
https://github.com/csi-addons/kubernetes-csi-addons/pull/25
https://github.com/csi-addons/kubernetes-csi-addons/pull/25/checks?check_run_id=4605948550
=> ci: match gh action job names with mergifyio rules

config/rbac/role.yaml, controllers/networkfence_controller.go
Add networkfence controller skeleton
Signed-off-by: Yug Gupta <yuggupta27@gmail.com>
=> controller: add networkfence skeleton

sidecar/internal/service/reclaimspace.go, sidecar/main.go, vendor/github.com/kubernetes-csi/csi-lib-utils/accessmodes/access_modes.go, vendor/modules.txt
This commit adds the implementation of Reclaim Space
Operation.
=> Implementation of Reclaim Space operation

PROJECT, config/crd/kustomization.yaml, config/crd/patches/cainjection_in_networkfences.yaml, config/crd/patches/webhook_in_networkfences.yaml, config/rbac/networkfence_editor_role.yaml, config/rbac/networkfence_viewer_role.yaml, config/samples/csiaddons_v1alpha1_networkfence.yaml
Add missing files for the creation of NetworkFence custom resource definition.
Fixes: #50 
Signed-off-by: Yug Gupta <yuggupta27@gmail.com>
=> Deploy NetworkFence CRD 

README.md, config/manifests/bases/csi-addons.clusterserviceversion.yaml
The new mailinglist is live, and can be used. Let's promote it!
=> doc: promote the new csi-addons mailinglist

apis/csiaddons/v1alpha1/csiaddonsnode_types.go, config/crd/bases/csiaddons.openshift.io_csiaddonsnodes.yaml, controllers/csiaddons/csiaddonsnode_controller.go, deploy/controller/crds.yaml
=> fix codespell errors

cmd/manager/main.go, controllers/replication.storage/pvc_test.go, controllers/replication.storage/volumereplication_controller.go, controllers/replication.storage/volumereplicationclass_test.go
Added option to set MaxConcurrentReconciles for VolumeReplication which was pending and for all other controllers this is set in #203
=> set MaxConcurrentReconciles for VolumeReplication

config/rbac/role.yaml, controllers/csiaddons/reclaimspacejob_controller.go, deploy/controller/rbac.yaml
replication controller needs access to update the PVC, added missing RBAC in this PR.
=> replication: add missing rbac for replication

controllers/replication.storage/volumereplication_controller.go
This commit adds volumeReplicationInstance to simplify code
and passing around parameters in functions.
=> replication: add volumeReplicationInstance to simplify code

config/crd/bases/csiaddons.openshift.io_csiaddonsnodes.yaml, config/crd/bases/csiaddons.openshift.io_networkfences.yaml, config/crd/bases/csiaddons.openshift.io_reclaimspacecronjobs.yaml, config/crd/bases/csiaddons.openshift.io_reclaimspacejobs.yaml, config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml, config/crd/bases/replication.storage.openshift.io_volumereplications.yaml, deploy/controller/crds.yaml, deploy/controller/install-all-in-one.yaml, tools/go.mod, tools/go.sum, tools/vendor/github.com/operator-framework/operator-sdk/internal/olm/operator/registry/fbcindex/configMapWriter.go, tools/vendor/modules.txt, tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/crd.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/genall/genall.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/genall/output.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go, tools/vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
=> rebase: update controller-tools

.github/workflows/lint-extras.yaml, Dockerfile, build/Containerfile.sidecar, build/Containerfile.tools
Updates: https://github.com/csi-addons/kubernetes-csi-addons/issues/405
=> fix: enable hadolint linter in super linter

.github/dependabot.yml
updated dependabot configuration to have group rebase.
=> ci: update dependabot for group updates

.github/dependabot.yml
update group rules for dependabot for tools folder.
=> ci: update group rules for dependabot

controllers/replication.storage/volumereplication_controller.go
Just like NetworkFence operations should be sent to a preferred
Controller Server, VolumeReplication operations should be sent
there as well.
Updates: #422
Depends-on: #496 
=> replication: send VolumeReplication operations to the leading controller

controllers/csiaddons/reclaimspacejob_controller.go
Just like NetworkFence operations should be sent to a preferred
Controller Server, the OFFLINE ReclaimSpace operations should be sent
there as well.
Depends-on: #496 
Updates: #422
=> reclaimspace: send ControllerReclaimSpace operations to the leading controller

controllers/csiaddons/reclaimspacecronjob_controller_test.go
The test case was failing if the test was run at some particular time of the day.
For ex: If the test was triggered @0:15:0, the last scheduled time will be 23:15:0 of the previous day since we are setting it to an hour earlier than the current time. Now when we calculate the getNextSchedule, the next schedule will point to the current day, when the cron job is scheduled to run at midnight every day. So in this case, the lastMissed will be pointing to a valid time. This leads to some test cases to get unexpected value for the lastMissed time which expects it to be time.Time{}. Though we get the expected wantErr in such cases too, since we are comparing the other return values seperately.
To avoid such failures, this patch checks for multiple expected last scheduled times.
Also the last …
=> ci: fix TestGetNextSchedule failure

apis/replication.storage/v1alpha1/volumegroupreplicationcontent_types.go
fixed few typos from volumegroup snapshot to volume group replication.
=> fix: fix typos related to group replication

internal/controller/csiaddons/persistentvolumeclaim_controller.go
This commit adds a check in StorageClass event handler to filter out PVC not needed for Reconcile.
- If the StorageClass has ReclaimSpace annotation,
PVCs without ReclaimSpace annotations will be enqueued.
- If the StorageClass has KeyRotation annotation,
PVCs without the KeyRotation annotation will be enqueued.
=> fix pvc reclaimspace & keyrotation annotation filter

config/manifests/bases/clusterserviceversion.yaml.in
This PR updates the bundle's CSV cabapilities from Basic Install to Seamless Upgrades.
=> bundle: Update CSV capability to Seamless Upgrades

internal/controller/csiaddons/csiaddonsnode_controller.go
This fixes https://github.com/csi-addons/kubernetes-csi-addons/issues/764
=> fix(controller): ipv6 addresses were unsupported by the controller

sidecar/internal/volume-condition/platform/kubelet.go
Depending on the failure condition, accessing the volume in an unhealthy state may hang. `k8s.io/mount-utils.(*Mounter).IsMountPoint` calls the `stat` syscall, and it is possible that it does not return. This prevents any further updates of the condition for any volume.
By using `k8s.io/mount-utils.(*Mounter).List` and parsing the result, access to the volume itself is not needed, and hangs will not occur anymore.
Fixes: #849
=> volume-condition: prevent volume access in isMountpoint()
